# Generated by Django 2.0.1 on 2018-02-06 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(help_text='必须，仅允许不超过10个字母数字。', max_length=10, verbose_name='省')),
                ('city', models.CharField(help_text='必须，仅允许不超过10个字母数字。', max_length=10, verbose_name='市')),
                ('region', models.CharField(help_text='必须，仅允许不超过10个字母数字。', max_length=10, verbose_name='区')),
            ],
        ),
        migrations.CreateModel(
            name='attention',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='关注编号')),
                ('attentionTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='邀请编号')),
                ('invitationTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='phone number')),
                ('gender', models.CharField(max_length=2, verbose_name='性别')),
                ('username', models.CharField(max_length=24, verbose_name='昵称')),
                ('name', models.CharField(max_length=10, verbose_name='真实姓名')),
                ('height', models.CharField(max_length=6, verbose_name='身高（厘米）')),
                ('income', models.CharField(max_length=100, verbose_name='年薪（人民币）')),
                ('wechat', models.CharField(max_length=30, verbose_name='微信号')),
                ('introduce', models.CharField(max_length=1024, verbose_name='自我介绍')),
                ('department', models.CharField(max_length=1024, verbose_name='工作单位')),
                ('station', models.CharField(max_length=80, verbose_name='工作岗位')),
                ('hometown', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='hometown_list', to='dating.Area')),
                ('residence', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='residence_list', to='dating.Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invitation',
            name='invetee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='invitee_list', to='dating.Member'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='invitationNum',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='invitation_list', to='dating.Member'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='inviter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inviter_list', to='dating.Member'),
        ),
        migrations.AddField(
            model_name='attention',
            name='befollowed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='followed_list', to='dating.Member'),
        ),
        migrations.AddField(
            model_name='attention',
            name='follower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='follower_list', to='dating.Member'),
        ),
    ]
